apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-portfolio
spec:
  replicas: 0
  selector:
    matchLabels:
      app: resume-portfolio
  template:
    metadata:
      labels:
        app: resume-portfolio
    spec:
      containers:
      - name: resume-portfolio
        image: abhidocker948/resume_portfolio:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resume-portfolio-service
spec:
  type: NodePort
  selector:
    app: resume-portfolio
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
